FROM docker.io/mchakravarty/app-tools-default

ENV LANG=C.UTF-8

ARG ACCELERATE=1.4.0.0
ARG CONTAINERS_ACCELERATE=0.1.0.0
ARG HASHABLE_ACCELERATE=0.1.0.0
ARG COLOUR_ACCELERATE=0.4.0.0
ARG MWC_RANDOM_ACCELERATE=0.2.0.0

RUN set -eux; \
    cabal install -j6 accelerate-${ACCELERATE} accelerate-llvm-native-${ACCELERATE} \
      containers-accelerate-${CONTAINERS_ACCELERATE} hashable-accelerate-${HASHABLE_ACCELERATE} \
      colour-accelerate-${COLOUR_ACCELERATE} mwc-random-accelerate-${MWC_RANDOM_ACCELERATE}; \
    \
    rm -rf /root/.cabal/packages /root/.cabal/dist-new /root/.cabal/logs /root/.local/bin; \

# NB: We leave the `configuration.json` of the base image in place, as we didn't touch any tools.
